apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nsip-gateway
  namespace: nsip
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "api.nsip.gov"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-gateway-vs
  namespace: nsip
spec:
  hosts:
  - "api.nsip.gov"
  gateways:
  - nsip-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: api-gateway.nsip.svc.cluster.local
        port:
          number: 80
